### ISSUE TITLE
关于Mindboggle数据集

### ISSUE THREAD

**Issue by RexEmperor** [ZAX130/RDP#8]
@ZAX130 
您好，我在Mindboggle101_release3中没有发现MMRR-19
![image](https://github.com/user-attachments/assets/65b4b753-9ea2-4a1b-a8f1-ab02b523d7c3)
但是文章中是说的MMRR-19和MMRR-21都用来做测试的，请问MMRR-19到哪里下载？
![image](https://github.com/user-attachments/assets/1dd72ce8-7362-42d7-aca2-66c66622f522)

**Comment by ZAX130** [comment]
MMRR-21里经过仿射的数据中有两个方向错了，把它们剔除后就是19例了

**Comment by RexEmperor** [comment]
@ZAX130 
请问这个应该怎么剔除？

**Comment by ZAX130** [comment]
用itk-snap软件从外观上观察的

**Comment by Pull2MAX** [comment]
## 我用snap看了一下，做aff的话应该是1号和21号反了，需要踢掉，桥哥我说的对吗
![image](https://github.com/user-attachments/assets/6cbc5716-709c-460e-a9ed-859a0a3e2414)

**Comment by ZAX130** [comment]
对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月7日(周二) 下午3:39
收件人: ***@***.***&gt;;
抄送: "Haiqiao ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ZAX130/RDP] 关于Mindboggle数据集 (Issue #8)




 
我用snap看了一下，做aff的话应该是1号和21号反了，需要踢掉，桥哥我说的对吗
 
image.png (view on web)

**Comment by RexEmperor** [comment]
> ## 我用snap看了一下，做aff的话应该是1号和21号反了，需要踢掉，桥哥我说的对吗
> ![image](https://github.com/user-attachments/assets/6cbc5716-709c-460e-a9ed-859a0a3e2414)

请问这个应该怎么剔除呀？是在python里剔除吗？

**Comment by ZAX130** [comment]
对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月19日(周三) 下午5:27
收件人: ***@***.***&gt;;
抄送: "Haiqiao ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ZAX130/RDP] 关于Mindboggle数据集 (Issue #8)


    
我用snap看了一下，做aff的话应该是1号和21号反了，需要踢掉，桥哥我说的对吗
 
image.png (view on web)
  
请问这个应该怎么剔除呀？是在python里剔除吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  RexEmperor left a comment (ZAX130/RDP#8)
  
我用snap看了一下，做aff的话应该是1号和21号反了，需要踢掉，桥哥我说的对吗
 
image.png (view on web)
  
请问这个应该怎么剔除呀？是在python里剔除吗？

**Comment by RexEmperor** [comment]
请问能把您对数据进行剔除的代码发一下吗？

**Comment by RexEmperor** [comment]
请问能把您对数据进行剔除的代码发一下吗？

**Comment by ZAX130** [comment]
就是删了啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月20日(周四) 中午1:16
收件人: ***@***.***&gt;;
抄送: "Haiqiao ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ZAX130/RDP] 关于Mindboggle数据集 (Issue #8)


   
请问能把您对数据进行剔除的代码发一下吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  RexEmperor left a comment (ZAX130/RDP#8)
 
请问能把您对数据进行剔除的代码发一下吗？

**Comment by RexEmperor** [comment]
我现在是在您的模型基础上进行了优化，然后目前在LPBA40数据集上进行测试了DSC，如果我想测试剩余几个指标该怎么进行呢？在您提供的代码中没有给到。

**Comment by ZAX130** [comment]
学一下medpy



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月20日(周四) 晚上6:55
收件人: ***@***.***&gt;;
抄送: "Haiqiao ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ZAX130/RDP] 关于Mindboggle数据集 (Issue #8)


   
我现在是在您的模型基础上进行了优化，然后目前在LPBA40数据集上进行测试了DSC，如果我想测试剩余几个指标该怎么进行呢？在您提供的代码中没有给到。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  RexEmperor left a comment (ZAX130/RDP#8)
 
我现在是在您的模型基础上进行了优化，然后目前在LPBA40数据集上进行测试了DSC，如果我想测试剩余几个指标该怎么进行呢？在您提供的代码中没有给到。
